property_web/authentication/urls.py
from django.urls import path
from .views import (
    UserSignupView,
    UserLoginView,
    ChangePasswordView,
    UserLogoutView,
    )

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('signup/', UserSignupView.as_view(), name='signup'),
    path('changepassword/', ChangePasswordView.as_view(), name='change_password'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
]

property_web/posts/urls.py
from django.urls import path
from .views import CreatePostView, PostDetailView, UpdatePostView, ListPostView, PostDeleteView

urlpatterns = [
    path('', ListPostView.as_view(), name='list_posts'),
    path('create/', CreatePostView.as_view(), name='create_post'),
    path('<str:post_id>/', PostDetailView.as_view(), name='post_detail'),
    path('<str:post_id>/update/', UpdatePostView.as_view(), name='update_post'),
    path('<uuid:post_id>/delete/', PostDeleteView.as_view(), name='delete_post')
]

property_web/property_web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.views.generic import RedirectView
from django.conf.urls.static import static
from .views import HomePageView

urlpatterns = [
    path('', RedirectView.as_view(url='/home', permanent=False)),
    path('home', HomePageView.as_view(), name='home'),
    path('user/', include('users.urls')),
    path('auth/', include('authentication.urls')),
    path("admin/", admin.site.urls),
    path('posts/', include('posts.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

property_web/authentication/models.py
from django.db import models

# Create your models here.

property_web/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator

from property_web.models import BaseModel


class CustomUser(AbstractUser, BaseModel):
    """
    A custom user model with phone number field.

    This model is used to represent users in the system. It inherits from
    Django's built-in AbstractBaseUser and also includes some additional fields
    from the BaseModel.

    Attributes:
        phone_number (str): The phone number of the user. Must be a 10-digit
            number starting with '0'. This field is unique across all users.
    """

    phone_number = models.CharField(
        validators=[RegexValidator(r"^0\d{9}$")], max_length=10, unique=True
    )

    class Meta:
        db_table = 'auth_user'

    def __str__(self):
        """
        Return a string representation of the User object.
        """

        return str(self.username)

property_web/authentication/forms.py
from django.contrib.auth.forms import UserCreationForm
from users.models import CustomUser


class SignUpForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'phone_number', 'password1', 'password2')

property_web/authentication/views.py
from django.shortcuts import redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.views import LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import (
    PasswordChangeForm,
    AuthenticationForm,
)

from .forms import SignUpForm
from property_web.views import BaseView


class UserSignupView(BaseView):
    template_name = 'signup.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = SignUpForm()
        return context

    def post(self, request, *args, **kwargs):
        form = SignUpForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect("login")

        context = self.get_context_data(**kwargs)
        context['form'] = form

        return self.render_to_response(context)


class UserLoginView(BaseView):
    template_name = 'login.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = AuthenticationForm()
        return context

    def post(self, request, *args, **kwargs):
        form = AuthenticationForm(request, data=request.POST)

        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('home')

        context = self.get_context_data(**kwargs)
        context["form"] = form
        context["error"] = 'Tên đăng nhập hoặc mật khẩu không đúng, vui lòng đăng nhập lại'

        return self.render_to_response(context)


class ChangePasswordView(LoginRequiredMixin, BaseView):
    template_name = 'change_password.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = PasswordChangeForm(self.request.user)
        return context

    def post(self, request, *args, **kwargs):
        form = PasswordChangeForm(self.request.user, request.POST)

        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('login')

        context = self.get_context_data(**kwargs)
        context["form"] = form

        return self.render_to_response(context)


class UserLogoutView(LoginRequiredMixin, LogoutView):
    """
    This is function to log out account user
    """

    next_page = 'login'

property_web/authentication/templates/change_password.html
{% load static %}

{% block extrahead %}
  <link rel="stylesheet" href="{% static 'css/modal.css' %}" />
  <script src="https://cdn.tailwindcss.com"></script>
{% endblock extrahead %}

{% block content %}
<div id="changePasswordModal" class="modal-container">
  <div class="modal">
    <div class="modal-header">
      <h3 class="modal-title">Đổi mật khẩu</h3>
      <i id="closeBtn" class="close-btn fa-solid fa-xmark"></i>
    </div>
    <form
      id="changePasswordForm"
      action="{% url 'change_password' %}"
      method="post"
      style="margin-bottom: 20px"
    >
      {% csrf_token %}
      <div style="display: flex; flex-direction: column" class="form-group">
        <label for="old_password">Mật khẩu cũ:</label>
        <input
          style="border: 1px solid black; border-radius: 5px"
          class="textfiled-authen"
          type="password"
          id="old_password"
          name="old_password"
        />
      </div>
      <div style="display: flex; flex-direction: column" class="form-group">
        <label for="new_password1">Mật khẩu mới:</label>
        <input
          style="border: 1px solid black; border-radius: 5px"
          class="textfiled-authen"
          type="password"
          id="new_password1"
          name="new_password1"
        />
      </div>
      <div style="display: flex; flex-direction: column" class="form-group">
        <label for="new_password2">Nhập lại mật khẩu mới:</label>
        <input
          style="border: 1px solid black; border-radius: 5px"
          class="textfiled-authen"
          type="password"
          id="new_password2"
          name="new_password2"
        />
      </div>
      {% if form.errors %}
      <div class="alert alert-danger">
        <ul>
          {% for field, errors in form.errors.items %}
            {% for error in errors %}
              <li>{{ error }}</li>
            {% endfor %}
          {% endfor %}
        </ul>
      </div>
      {% endif %}
      <div
        id="form-errors"
        class="alert alert-danger"
        style="display: none"
      ></div>
      <div>
        <button type="submit" class="modal-btn">Lưu</button>
      </div>
    </form>
  </div>
</div>

{% block extrascripts %}
  <script src="{% static 'js/change_password.js' %}"></script>
{% endblock extrascripts %}

{% endblock %}

property_web/authentication/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/authen.css' %}" />
    <title>Login</title>
  </head>
  <body>
    <div class="login-container">
      <h2 class="title">Đăng nhập</h2>
      <form method="post" class="login-form">
        {% csrf_token %}
        <div class="login">
          <div class="form-group">
            <label for="id_username">Tên đăng nhập:</label>
            {{ form.username }}
          </div>

          <div class="form-group">
            <label for="id_password">Mật khẩu:</label>
            {{ form.password }}
          </div>

          <button type="submit" class="login-btn">Đăng nhập</button>

          {% if error %}
          <p class="error">{{ error }}</p>
          {% endif %}
        </div>
      </form>
      <p>
        Bạn chưa có tài khoản?
        <a href="{% url 'signup' %}" class="signup-link">Đăng kí</a>
      </p>
    </div>
  </body>
</html>

property_web/authentication/templates/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/authen.css' %}" />
    <title>Signup</title>
  </head>
  <body>
    <div class="signup-container">
      <h2 class="title">Đăng kí</h2>
      <form method="post" class="signup-form">
        {% csrf_token %}
        <div class="signup">
          <div class="form-group">
            <label for="id_username">Tên đăng nhập:</label>
            <input type="text" id="id_username" name="username" />
          </div>
          <div class="form-group">
            <label for="id_email">Email:</label>
            <input type="email" id="id_email" name="email" />
          </div>
          <div class="form-group">
            <label for="id_phone_number">Số điện thoại:</label>
            <input type="text" id="id_phone_number" name="phone_number" />
          </div>
          <div class="form-group">
            <label for="id_password1">Mật khẩu:</label>
            <input type="password" id="id_password1" name="password1" />
          </div>
          <div class="form-group">
            <label for="id_password2">Nhập lại mật khẩu:</label>
            <input type="password" id="id_password2" name="password2" />
          </div>
          {% if form.errors %}
          <div class="error-list">
            {% for field in form %} {% for error in field.errors %}
            <span class="error">{{ error }}</span>
            {% endfor %} {% endfor %}
          </div>
          {% endif %}
          <button type="submit" class="signup-btn">Đăng kí</button>
        </div>
      </form>
      <p>
        Bạn đã có tài khoản?
        <a href="{% url 'login' %}" class="login-link">Đăng nhập</a>
      </p>
    </div>
  </body>
</html>